/**
 * Toshkent atrofi — demo mijozlar + buyurtma (qayerdan/qayerga, vaqt, narx, aloqa).
 */
export const DEMO_CLIENT_MARKERS = {
  'demo-mijoz-chorsu': {
    role: 'client',
    pos: [41.3258, 69.2284],
    label: 'Demo mijoz · Chorsu',
    order: {
      orderKind: 'local',
      from: 'Chorsu metro',
      to: 'Yunusobod 12-mahalla, 8-uy',
      when: 'Srochno (30 daqiqa ichida)',
      price: '45 000 – 60 000 so‘m (kelishiladi)',
      phone: '+998901112233',
      telegram: '@demo_mijoz_1',
    },
  },
  'demo-mijoz-mustaqillik': {
    role: 'client',
    pos: [41.311, 69.2795],
    label: 'Demo mijoz · Mustaqillik maydoni',
    order: {
      orderKind: 'local',
      from: 'Mustaqillik maydoni',
      to: 'Sergeli 6-mavze',
      when: 'Bugun 20:15',
      price: '55 000 so‘m dan (kelishiladi)',
      phone: '+998902223344',
      telegram: 'toshkent_taxi_demo',
    },
  },
  'demo-mijoz-chilonzor': {
    role: 'client',
    pos: [41.2845, 69.205],
    label: 'Demo mijoz · Chilonzor',
    order: {
      orderKind: 'local',
      from: 'Chilonzor 19-mahalla',
      to: 'Aeroport',
      when: 'Srochno',
      price: 'Kelishiladi (taxminan 80 000)',
      phone: '+998903334455',
      telegram: '@chilonzor_demo',
    },
  },
  'demo-mijoz-yunusobod': {
    role: 'client',
    pos: [41.3645, 69.288],
    label: 'Demo mijoz · Yunusobod',
    order: {
      orderKind: 'local',
      from: 'Yunusobod 14-mahalla',
      to: 'Buyuk ipak yo‘li metro',
      when: 'Ertaga 09:00',
      price: '30 000 – 40 000 so‘m',
      phone: '+998904445566',
      telegram: '',
    },
  },
  'demo-mijoz-sergeli': {
    role: 'client',
    pos: [41.228, 69.216],
    label: 'Demo mijoz · Sergeli',
    order: {
      orderKind: 'local',
      from: 'Sergeli bozori',
      to: 'Chorsu',
      when: 'Srochno',
      price: 'Kelishiladi',
      phone: '',
      telegram: '@sergeli_demo',
    },
  },
  'demo-mijoz-yakkasaroy': {
    role: 'client',
    pos: [41.282, 69.256],
    label: 'Demo mijoz · Yakkasaroy',
    order: {
      orderKind: 'local',
      from: 'Yakkasaroy tumani',
      to: 'TTZ',
      when: 'Bugun 21:30 dan keyin',
      price: '50 000 so‘m atrofida',
      phone: '+998905556677',
      telegram: '@yakkasaroy_user',
    },
  },
  'demo-mijoz-mirzo': {
    role: 'client',
    pos: [41.315, 69.248],
    label: 'Demo mijoz · Mirzo Ulug‘bek',
    order: {
      orderKind: 'local',
      from: 'Mirzo Ulug‘bek 6-mahalla',
      to: 'Olmazor metro',
      when: 'Srochno',
      price: '25 000 – 35 000 (kelishiladi)',
      phone: '+998906667788',
      telegram: '@mirzo_demo',
    },
  },
  'demo-mijoz-bektemir': {
    role: 'client',
    pos: [41.21, 69.33],
    label: 'Demo mijoz · Bektemir',
    order: {
      orderKind: 'local',
      from: 'Bektemir tumani',
      to: 'Markaz (Chorsu)',
      when: 'Ertaga 07:00',
      price: 'Kelishiladi',
      phone: '+998907778899',
      telegram: '',
    },
  },
  'demo-mijoz-mirobod': {
    role: 'client',
    pos: [41.298, 69.232],
    label: 'Demo mijoz · Mirobod',
    order: {
      orderKind: 'local',
      from: 'Mirobod ko‘chasi',
      to: 'Qatortol bozori',
      when: 'Srochno yoki 19:00 gacha',
      price: '40 000 so‘m',
      phone: '+998908889900',
      telegram: '@mirobod_demo',
    },
  },
  'demo-mijoz-shayxontohur': {
    role: 'client',
    pos: [41.334, 69.221],
    label: 'Demo mijoz · Shayxontohur',
    order: {
      orderKind: 'local',
      from: 'Shayxontohur',
      to: 'Novza metro',
      when: 'Bugun 22:00',
      price: 'Kelishiladi (taksi bilan)',
      phone: '+998909990011',
      telegram: '@shayxon_demo',
    },
  },
};
